---
title: "BMS_jobs"
author: "Victoria_Binimelis_Vadell"
date: "12/5/2021"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

## BMS_charts

Charts by parameter of the BMS jobs

## GVCC


```{r pressure, echo=FALSE}
library("jsonlite")
library(ggplot2)


##agafam el JSON de la URL i el convertim en dataframe
btc <- jsonlite::fromJSON("http://hotelconnect-scheduler.live.service/hotelconnect-scheduler/scheduler/list")
jobs_data_frame <- as.data.frame(btc)

##accedim al segon nivell de JSON/dataframe
jobs_data_frame_2 <- do.call(data.frame, jobs_data_frame)

##eliminam els jobs de disney
jobs_data_frame_3<-subset(jobs_data_frame_2, jobInfos.jobName!="disneyBMSJob" & jobInfos.jobName!="disneyCalendarJobHB"
                          & jobInfos.jobName!="disneyCalendarJobLB" & jobInfos.jobName!="disneyCalendarJobWB")


##conertim els NA en FALSE
jobs_data_frame_3["jobInfos.properties.GVCC"][is.na(jobs_data_frame_3["jobInfos.properties.GVCC"])]<-FALSE
jobs_data_frame_3["jobInfos.properties.Breakdown"][is.na(jobs_data_frame_3["jobInfos.properties.Breakdown"])]<-FALSE
jobs_data_frame_3["jobInfos.properties.isFinalStatus"][is.na(jobs_data_frame_3["jobInfos.properties.isFinalStatus"])]<-FALSE
jobs_data_frame_3["jobInfos.properties.holderNameAllPax"][is.na(jobs_data_frame_3["jobInfos.properties.holderNameAllPax"])]<-FALSE
jobs_data_frame_3["jobInfos.properties.pmsRoomCode"][is.na(jobs_data_frame_3["jobInfos.properties.pmsRoomCode"])]<-FALSE


##GVCC
GVCC<-ggplot(jobs_data_frame_3, aes(x = factor (jobInfos.properties.GVCC)))+
  geom_bar(fill = "#3995e6", width = 0.5)+
  labs(x = "GVCC",y = "Count")+
  geom_text(aes(label = ..count..), stat = "count", vjust =-0.25, colour = "black", position=position_dodge(width=0.9))

GVCC + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                 panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  coord_cartesian(ylim = c(10, 200))

```

## CBD

```{r echo=FALSE}

CBD<-ggplot(jobs_data_frame_3, aes(x = factor (jobInfos.properties.Breakdown)))+
  geom_bar(fill = "#3995e6", width = 0.5)+
  labs(x = "CBD",y = "Count")+
  geom_text(aes(label = ..count..), stat = "count", vjust =-0.25, colour = "black", position=position_dodge(width=0.9))

CBD + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
      panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  coord_cartesian(ylim = c(10, 200))
```

## isFinalStatus
```{r echo=FALSE}
isFinalStatus<-ggplot(jobs_data_frame_3, aes(x = factor (jobInfos.properties.isFinalStatus)))+
  geom_bar(fill = "#3995e6", width = 0.5)+
  labs(x = "isFinalStatus",y = "Count")+
  geom_text(aes(label = ..count..), stat = "count", vjust =-0.25, colour = "black", position=position_dodge(width=0.9))

isFinalStatus + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
            panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  coord_cartesian(ylim = c(10, 200))
```

## holderNameAllPax

```{r echo=FALSE}
holderNameAllPax<-ggplot(jobs_data_frame_3, aes(x = factor (jobInfos.properties.holderNameAllPax)))+
  geom_bar(fill = "#3995e6", width = 0.5)+
  labs(x = "holderNameAllPax",y = "Count")+
  geom_text(aes(label = ..count..), stat = "count", vjust =-0.25, colour = "black", position=position_dodge(width=0.9))

holderNameAllPax + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                      panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  coord_cartesian(ylim = c(10, 200))
```

## pmsRoomCode

```{r echo=FALSE}
pmsRoomCode<-ggplot(jobs_data_frame_3, aes(x = factor (jobInfos.properties.pmsRoomCode)))+
  geom_bar(fill = "#3995e6", width = 0.5)+
  labs(x = "pmsRoomCode",y = "Count")+
  geom_text(aes(label = ..count..), stat = "count", vjust =-0.25, colour = "black", position=position_dodge(width=0.9))

pmsRoomCode + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                         panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  coord_cartesian(ylim = c(10, 200))
```



